### ISSUE TITLE
toolchains selection issue when building BBL

### ISSUE THREAD

**Issue by tongchen126** [litex-hub/linux-on-litex-rocket#22]
In the fourth step of this [section](https://github.com/litex-hub/linux-on-litex-rocket#building-the-software-bootbin-busybox-linux-and-bbl), the toolchains is configured to use 'riscv64-unknown-linux-gnu'. However, this toolchains is for compiling Linux executable files(i.e., for compiling application on top of Linux with libraries support and not for executing on the bare machine, like bootloader). And the use of this toolchains will trigger errors when compiling bbl.   
On the other hand, 'riscv64-unknown-elf' toolchains should be the right choice to compile bbl(for the bare machine), which can be found on this [comment](https://github.com/tongchen126/Boot-Debian-On-Litex-Rocket/issues/1#issuecomment-1073268903) by @developandplay.  

Encountered error when using 'riscv64-unknown-linux-gnu':
![bbl_error](https://user-images.githubusercontent.com/31961076/159258539-7fd1a4ca-4148-4869-b9f3-dd3ed24a3865.png)
  
'riscv64-unknown-elf' is fine with this:
![bbl](https://user-images.githubusercontent.com/31961076/159258671-a90738f3-166c-47c9-8a35-e31a848db413.png)

**Comment by gsomlo** [comment]
In my experience, `riscv64-unknown-elf` is a subset of `riscv64-unknown-linux-gnu`. If the former works for you but the latter does not, it's probably because the latter is somehow misconfigured or missing part of its installation. The prebuilt toolchain linked in the `README` (at `http://www.contrib.andrew.cmu.edu/~somlo/BTCP/RISCV-toolchain.tar.xz`) has both `*-elf` and `*-linux-gnu`, and both work just fine for me. Of course, `*-elf` is ***sufficient*** to build self-contained blobs (e.g., firmware, kernel), and `*-linux-gnu` is ***required*** to build programs linked against glibc, so definitely feel free to restrict yourself to using `*-elf` whenever that's suitable!

Hope this helps!
